-- ADR-013 (docs/adr/013-project-site-id-obligatorio.md): `project.site_id`
-- pasa a NOT NULL. Primer caso real de la convención NOT VALID + VALIDATE
-- de CLAUDE.md §6: un `ALTER COLUMN ... SET NOT NULL` directo revisa la
-- tabla entera bajo un lock exclusivo de una sola pasada. Acá se separa en
-- dos despliegues:
--   1. Este archivo: agrega un CHECK equivalente con NOT VALID (instantáneo,
--      no mira filas existentes) — a partir de acá toda fila NUEVA ya exige
--      site_id, sin haber tocado ninguna fila vieja todavía.
--   2. project_site_id_not_null_validate.sql, un PR aparte que se abre
--      después de que ESTE despliegue (con el backfill de abajo ya corrido)
--      esté en el servidor: valida el CHECK, recién ahí convierte la
--      columna a NOT NULL de verdad (Postgres se salta el escaneo completo
--      porque ya hay un CHECK validado que prueba lo mismo) y borra el
--      CHECK, ya redundante. No va en este PR — si las dos quedaran
--      pendientes en la misma corrida de `pnpm db:migrate`, el migrador las
--      aplicaría en una sola transacción y el VALIDATE prolongaría el lock
--      exclusivo del ADD, exactamente el problema que NOT VALID existe para
--      evitar (verificado: `packages/db/node_modules/drizzle-orm/pg-core/dialect.js:60`,
--      `PgDialect.migrate` envuelve todas las migraciones pendientes de una
--      corrida en un único `session.transaction(...)`).
--
-- Divergencia intencional entre lo que este archivo aplica y lo que
-- packages/db/src/schema/projects/schema.ts + meta/0009_snapshot.json
-- declaran: el esquema de Drizzle ya tiene `siteId: uuid('site_id').notNull()`,
-- y el snapshot de esta misma migración ya registra la columna como NOT
-- NULL — pero lo único que esta migración aplica de verdad es el CHECK
-- NOT VALID de más abajo. La base, después de este despliegue, sigue
-- teniendo `site_id` nullable a nivel de catálogo (`attnotnull = false`);
-- lo único que cambia es que ninguna fila NUEVA puede tener site_id null
-- desde acá (el CHECK ya rige hacia adelante, aunque no esté validado
-- contra las filas viejas). Es la misma anticipación que ya usa la
-- convención de CLAUDE.md §6 para ampliar un CHECK (el esquema declara el
-- estado final desde el primer paso, la base lo alcanza recién en el
-- último) — acá es la primera vez que se aplica a una columna que pasa a
-- NOT NULL, no a un CHECK que cambia de valores.
--
-- Va en la dirección seguridad, no al revés: si alguien corriera
-- `pnpm db:generate` entre este despliegue y el de `..._validate.sql`, no
-- va a ver ninguna diferencia que generar (el esquema y el snapshot ya
-- coinciden) — por eso `..._validate.sql` no puede generarse con
-- `drizzle-kit generate` normal, necesita `--custom` (un archivo vacío
-- para llenar a mano), igual que este archivo. La divergencia nunca deja
-- pasar un `ALTER` peligroso sin querer: en el peor caso, alguien asume
-- que la columna ya es NOT NULL cuando en la base real hasta puede tener
-- nulos (filas viejas, antes del backfill) — un supuesto optimista sobre
-- datos, no una migración que se salte una validación.
--
-- Consecuencia concreta mientras las dos migraciones no estén las dos
-- desplegadas: el tipo de `ProjectRow['siteId']` en TypeScript (derivado
-- del esquema de Drizzle) es `string`, no `string | null` — pero una fila
-- de `project` creada antes de este despliegue, en un ambiente que
-- todavía no corrió el backfill, puede tener `site_id` null en la base de
-- verdad. Ningún código de este PR lee `project.site_id` con ese supuesto
-- (el hook y el script solo escriben), pero cualquier código nuevo que sí
-- lo lea antes de que `..._validate.sql` esté desplegado tiene que saber
-- que el tipo miente en esa ventana.
--
-- Antes de que el paso 2 llegue a un ambiente con datos reales, hay que
-- correr el backfill (`apps/api/src/scripts/ensure-default-sites.ts`):
-- crea el sitio por defecto de toda organización que todavía no tenga
-- ninguno, y completa `site_id` en los proyectos que lo tengan null. Sin
-- eso, el VALIDATE del paso 2 falla apenas encuentra la primera fila vieja
-- con `site_id` null — falla segura (el despliegue se aborta), no corrompe
-- nada, pero hay que correrlo antes para que no pase. Comando exacto,
-- necesita `DATABASE_URL`/`BETTER_AUTH_SECRET`/`BETTER_AUTH_URL` del
-- ambiente (`loadServerEnv`, `packages/config`) y el build compilado
-- primero (`tsx` no es una dependencia de `apps/api`, a diferencia de
-- `packages/db/src/migrate.ts`):
--   pnpm --filter @orq/api build && pnpm --filter @orq/api db:ensure-default-sites
--
-- SET LOCAL, no SET a secas: un SET a secas sobrevive al COMMIT de esta
-- migración y queda pegado a la conexión del pool de `app_owner`, afectando
-- migraciones siguientes de otras tablas que no lo necesitan. SET LOCAL
-- rige solo hasta el fin de esta transacción/corrida.
SET LOCAL lock_timeout = '5s';
ALTER TABLE "project" ADD CONSTRAINT "project_site_id_not_null" CHECK ("site_id" IS NOT NULL) NOT VALID;
